/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  community: [
    {
      type: 'autogenerated',
      dirName: 'community', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  support: [
    {
      type: 'autogenerated',
      dirName: 'support', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  tutorial: [
    {
      type: 'autogenerated',
      dirName: 'tutorial', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  documentation: [
    {
      type: 'autogenerated',
      dirName: 'documentation', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
    // {
    //   type: 'category',
    //   label: 'Actions',
    //   items: [
    //     {type: 'autogenerated', dirName: 'actions'},
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'intro',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Getting Started',
    //   items: [
    //     {
    //       type: 'doc',
    //       id: 'intro',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'AutoFlow',
    //   items: [
    //     {type: 'autogenerated', dirName: 'docs.apiautoflow.com'},
    //   ],
    // },
    // {
    //   type: 'link',
    //   label: 'Learn more',
    //   href: 'https://example.com',
    // },
  ],
};

module.exports = sidebars;
